import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GeneralNavComponent from "@/components/navs/general-nav/general-nav.component";
import GeneralFooterComponent from "@/components/footers/general-footer/general-footer.component";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Turn up",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background`}
      >
        <GeneralNavComponent />
        <div className="min-h-[calc(100vh-70px)]">{children}</div>
        <GeneralFooterComponent />
      </body>
    </html>
  );
}
